[tool.poetry]
name = "rberga06-utils"
version = "0.1.0"
description = ""
authors = ["RBerga06 <78449715+RBerga06@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "rberga06", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^1.10.7"
packaging = "^23.0"
pyyaml = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
