[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "--cov=rberga06.utils --cov-report html"

[tool.poetry]
name = "rberga06-utils"
version = "0.1.0"
description = ""
authors = ["RBerga06 <78449715+RBerga06@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "rberga06", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = {version = "^2.0a1", allow-prereleases = true}
packaging = "^23.0"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
