name: Main workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # test on all supported platforms
  test:
    strategy:
      fail-fast: false
      matrix:
        # os: [ "ubuntu", "macos", "windows" ]
        # python: [ "3.11", "3.12.0-alpha.7" ]
        os: [ "ubuntu", "windows" ]
        python: [ "3.11" ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install poetry
      run: pip install poetry
    - name: Editable install
      run: poetry install --with=dev
    - name: Test
      run: poetry run pytest

  # (Platform/Python)-indipendent build: run once (ubuntu, python 3.11)
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install build
      run: pip install build
    - name: Build
      run: python -m build
    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl
    - name: Upload source distribution
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/*.tar.gz
